datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: ${JDBC_DATABASE_URL}
  production:
    driver: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
